version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Build with MSBuild
          command: msbuild -p:Configuration=release

      - store_artifacts:
          path: x64/Release
      - persist_to_workspace:
          root: x64/Release
          paths:
            - ./

  test:
    executor:
      name: windows/default
    steps:
      - run:
          name: Start WPR
          command: wpr -start GeneralProfile
      - attach_workspace:
          at: ./
      - run:
          name: Run normally with 4 GiB RAM consumption
          command: |
            .\HelloVCExe.exe 4096
      - run:
          name: Run native unit tests
          command: |
            & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" .\HelloVCTest.dll /InIsolation /platform:Win32
      - run:
          name: Stop WPR
          command: wpr -stop wpr.etl
          when: always
      - store_artifacts:
          path: wpr.etl

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
